-- ANIMAL_INS.DATETIME ~ ANIMAL_OUTS.DATETIME 사이의 DATEDIFF로 정렬하면 됨.

SELECT
    ai.ANIMAL_ID,
    ai.NAME
FROM
    ANIMAL_INS ai
INNER JOIN
    ANIMAL_OUTS ao
ON
    ai.ANIMAL_ID = ao.ANIMAL_ID
ORDER BY
    DATEDIFF(ao.DATETIME, ai.DATETIME) DESC
LIMIT
    2