SELECT 
    ri.REST_ID, 
    ri.REST_NAME,
    ri.FOOD_TYPE,
    ri.FAVORITES,
    ri.ADDRESS,
    ROUND(AVG(rr.REVIEW_SCORE),2) as SCORE
FROM REST_INFO as ri
INNER JOIN REST_REVIEW as rr ON ri.REST_ID = rr.REST_ID
WHERE ri.ADDRESS LIKE '서울%'
GROUP BY ri.REST_ID
ORDER BY SCORE DESC, ri.FAVORITES DESC;