(
SELECT
    CAR_ID,
    '대여중' AS AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY rent
WHERE
    START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
)
UNION
(
SELECT
    CAR_ID,
    '대여 가능' AS AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY rent
WHERE
    CAR_ID NOT IN (
        SELECT
             CAR_ID
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY rent
        WHERE
            START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
    )
)
ORDER BY
CAR_ID DESC;