WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR 
    UNION ALL 
    SELECT HOUR + 1 
        FROM HOURS
        WHERE HOUR < 23
)

SELECT
    HOUR,
    COUNT(ANIMAL_ID) as COUNT
FROM
    HOURS h
LEFT OUTER JOIN
    ANIMAL_OUTS ao
ON
    h.HOUR = HOUR(ao.DATETIME)
GROUP BY
    h.HOUR
ORDER BY
    h.HOUR ASC;

# SELECT
#     HOUR(DATETIME) as HOUR,
#     COUNT(ANIMAL_ID) as COUNT
# FROM
#     ANIMAL_OUTS ao
# RIGHT OUTER JOIN
#     HOURS h
# ON
#     HOUR(ao.DATETIME) = h.HOUR
# GROUP BY
#     h.HOUR
# ORDER BY
#     h.HOUR ASC;